
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: AssetStorage_development

test:
  <<: *default
  database: AssetStorage_test

production:
  <<: *default
  database: AssetStorage_production
  username: postgres
  password: pradip
